export const Products = [
  {
    id: 1,
    name: 'Basic T-Shirt',
    description: '100% cotton basic t-shirt, available in various colors.',
    longDescription:
      "This basic t-shirt is made from 100% premium cotton, ensuring a soft and comfortable feel. It's perfect for layering or wearing on its own. Available in a range of colors to suit any wardrobe, this tee is a versatile staple you'll reach for again and again.",
    price: 19.99,
    oldPrice: 24.99,
    discount: 20,
    category: 'T-Shirts',
    image: 'https://example.com/images/basic_tshirt.jpg',
    rating: 4.5,
    stock: 120,
    SKU: 'TSHIRT001',
  },
  {
    id: 2,
    name: 'Slim Fit Jeans',
    description: 'Slim fit jeans with a modern cut, perfect for casual wear.',
    longDescription:
      'These slim fit jeans are designed with a modern, flattering cut that hugs your body while still providing comfort. Made from high-quality denim, they are durable and long-lasting, making them a perfect choice for both casual and semi-formal occasions.',
    price: 49.99,
    oldPrice: 59.99,
    discount: 17,
    category: 'Jeans',
    image: 'https://example.com/images/slim_fit_jeans.jpg',
    rating: 4.3,
    stock: 80,
    SKU: 'JEANS001',
  },
  {
    id: 3,
    name: 'Denim Jacket',
    description: 'Classic denim jacket with button front closure.',
    longDescription:
      "Our classic denim jacket features a button front closure and is crafted from durable denim. It's a timeless piece that pairs perfectly with any outfit, providing both style and warmth. Whether you're dressing up or down, this jacket is a must-have.",
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Jackets',
    image: 'https://example.com/images/denim_jacket.jpg',
    rating: 4.7,
    stock: 50,
    SKU: 'JACKET001',
  },
  {
    id: 4,
    name: 'Chino Pants',
    description: 'Comfortable and stylish chino pants for everyday wear.',
    longDescription:
      "These chino pants combine comfort and style, making them ideal for everyday wear. Made from soft, breathable fabric, they offer a tailored fit that's perfect for the office or a night out. Available in multiple colors to complement any look.",
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Pants',
    image: 'https://example.com/images/chino_pants.jpg',
    rating: 4.4,
    stock: 100,
    SKU: 'PANTS001',
  },
  {
    id: 5,
    name: 'Plaid Shirt',
    description: 'Casual plaid shirt made from soft flannel fabric.',
    longDescription:
      "This plaid shirt is crafted from soft flannel fabric, providing comfort and warmth. It's perfect for layering during the cooler months or wearing on its own for a laid-back look. The classic plaid pattern adds a touch of rugged style to any outfit.",
    price: 29.99,
    oldPrice: 34.99,
    discount: 14,
    category: 'Shirts',
    image: 'https://example.com/images/plaid_shirt.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'SHIRT001',
  },
  {
    id: 6,
    name: 'Leather Belt',
    description: 'Genuine leather belt with a classic buckle.',
    longDescription:
      "This genuine leather belt is a timeless accessory that adds a touch of sophistication to any outfit. Featuring a classic metal buckle, it's perfect for both casual and formal wear. The durable leather ensures it will be a long-lasting addition to your wardrobe.",
    price: 19.99,
    oldPrice: 24.99,
    discount: 20,
    category: 'Accessories',
    image: 'https://example.com/images/leather_belt.jpg',
    rating: 4.8,
    stock: 200,
    SKU: 'BELT001',
  },
  {
    id: 7,
    name: 'Sneakers',
    description: 'Comfortable sneakers for everyday wear.',
    longDescription:
      'These sneakers are designed for comfort and durability, making them perfect for everyday wear. With a cushioned sole and breathable upper, they provide support and ventilation during all your daily activities. Available in multiple colors and styles.',
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Footwear',
    image: 'https://example.com/images/sneakers.jpg',
    rating: 4.5,
    stock: 150,
    SKU: 'SHOE001',
  },
  {
    id: 8,
    name: 'Wool Scarf',
    description: 'Soft wool scarf to keep you warm during winter.',
    longDescription:
      'This wool scarf is a winter essential, crafted from soft, high-quality wool. It provides excellent warmth and comfort, while its classic design makes it a versatile accessory that can be paired with any outfit.',
    price: 25.99,
    oldPrice: 32.99,
    discount: 21,
    category: 'Accessories',
    image: 'https://example.com/images/wool_scarf.jpg',
    rating: 4.7,
    stock: 180,
    SKU: 'SCARF001',
  },
  {
    id: 9,
    name: 'Puffer Jacket',
    description: 'Lightweight and warm puffer jacket, perfect for winter.',
    longDescription:
      'Stay warm without the bulk in this lightweight puffer jacket. Filled with high-quality insulation, it provides excellent warmth while remaining lightweight and comfortable. The jacket is also water-resistant, making it perfect for winter weather.',
    price: 89.99,
    oldPrice: 119.99,
    discount: 25,
    category: 'Jackets',
    image: 'https://example.com/images/puffer_jacket.jpg',
    rating: 4.6,
    stock: 70,
    SKU: 'JACKET002',
  },
  {
    id: 10,
    name: 'Graphic Tee',
    description: 'Trendy graphic t-shirt with unique print.',
    longDescription:
      "Make a statement with this trendy graphic tee. Featuring a unique print, it's made from soft, breathable fabric for all-day comfort. Pair it with jeans or shorts for a casual, stylish look.",
    price: 22.99,
    oldPrice: 29.99,
    discount: 23,
    category: 'T-Shirts',
    image: 'https://example.com/images/graphic_tee.jpg',
    rating: 4.3,
    stock: 130,
    SKU: 'TSHIRT002',
  },
  {
    id: 11,
    name: 'Hoodie',
    description: 'Cozy hoodie made from soft fleece.',
    longDescription:
      'This cozy hoodie is perfect for lounging or casual outings. Made from soft fleece, it provides warmth and comfort without being too heavy. The adjustable drawstring hood and kangaroo pocket add functionality and style.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Sweatshirts',
    image: 'https://example.com/images/hoodie.jpg',
    rating: 4.7,
    stock: 90,
    SKU: 'HOODIE001',
  },
  {
    id: 12,
    name: 'Canvas Tote Bag',
    description: 'Durable canvas tote bag, perfect for shopping.',
    longDescription:
      "This durable canvas tote bag is perfect for shopping or carrying everyday essentials. Made from heavy-duty canvas, it features sturdy handles and a spacious interior. Available in multiple colors, it's both practical and stylish.",
    price: 15.99,
    oldPrice: 19.99,
    discount: 20,
    category: 'Bags',
    image: 'https://example.com/images/canvas_tote.jpg',
    rating: 4.8,
    stock: 200,
    SKU: 'BAG001',
  },
  {
    id: 13,
    name: 'Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric.',
    longDescription:
      'These lightweight running shorts are designed for performance and comfort. Made from moisture-wicking fabric, they keep you cool and dry during your workouts. The elastic waistband ensures a secure fit, and the built-in liner provides additional support.',
    price: 25.99,
    oldPrice: 32.99,
    discount: 21,
    category: 'Shorts',
    image: 'https://example.com/images/running_shorts.jpg',
    rating: 4.4,
    stock: 140,
    SKU: 'SHORTS001',
  },
  {
    id: 14,
    name: 'Polo Shirt',
    description: 'Classic polo shirt with a ribbed collar.',
    longDescription:
      "This classic polo shirt features a ribbed collar and a comfortable, relaxed fit. Made from breathable cotton fabric, it's perfect for both casual and semi-formal occasions. The versatile design makes it a wardrobe essential.",
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shirts',
    image: 'https://example.com/images/polo_shirt.jpg',
    rating: 4.5,
    stock: 110,
    SKU: 'SHIRT002',
  },
  {
    id: 15,
    name: 'Winter Boots',
    description: 'Sturdy winter boots with waterproof exterior.',
    longDescription:
      'These sturdy winter boots are designed to keep your feet warm and dry in harsh weather conditions. Featuring a waterproof exterior and insulated lining, they provide excellent protection against the elements. The rugged sole ensures traction on slippery surfaces.',
    price: 99.99,
    oldPrice: 129.99,
    discount: 23,
    category: 'Footwear',
    image: 'https://example.com/images/winter_boots.jpg',
    rating: 4.7,
    stock: 60,
    SKU: 'BOOTS001',
  },
  {
    id: 16,
    name: 'Cargo Pants',
    description: 'Comfortable cargo pants with multiple pockets.',
    longDescription:
      'These comfortable cargo pants are perfect for outdoor activities or casual wear. Made from durable fabric, they feature multiple pockets for storing your essentials. The relaxed fit and adjustable waistband provide comfort and functionality.',
    price: 45.99,
    oldPrice: 59.99,
    discount: 23,
    category: 'Pants',
    image: 'https://example.com/images/cargo_pants.jpg',
    rating: 4.4,
    stock: 85,
    SKU: 'PANTS002',
  },
  {
    id: 17,
    name: 'Fleece Jacket',
    description: 'Warm fleece jacket with zippered pockets.',
    longDescription:
      'This warm fleece jacket is perfect for layering during the colder months. It features zippered pockets to keep your essentials secure and a full-zip front for easy wear. The soft fleece material provides comfort and warmth without adding bulk.',
    price: 49.99,
    oldPrice: 69.99,
    discount: 28,
    category: 'Jackets',
    image: 'https://example.com/images/fleece_jacket.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'JACKET003',
  },
  {
    id: 18,
    name: 'Sports Bra',
    description: 'High-impact sports bra with moisture-wicking fabric.',
    longDescription:
      'This high-impact sports bra is designed to provide support and comfort during intense workouts. Made from moisture-wicking fabric, it keeps you cool and dry. The adjustable straps and wide band offer a secure and customized fit.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Activewear',
    image: 'https://example.com/images/sports_bra.jpg',
    rating: 4.5,
    stock: 90,
    SKU: 'ACTIVE001',
  },
  {
    id: 19,
    name: 'Yoga Pants',
    description: 'Flexible and comfortable yoga pants with a high waistband.',
    longDescription:
      'These yoga pants are designed for flexibility and comfort, with a high waistband that provides support and coverage. The stretchy fabric allows for a full range of motion, making them perfect for yoga, Pilates, or any other workout.',
    price: 34.99,
    oldPrice: 44.99,
    discount: 22,
    category: 'Activewear',
    image: 'https://example.com/images/yoga_pants.jpg',
    rating: 4.7,
    stock: 100,
    SKU: 'ACTIVE002',
  },
  {
    id: 20,
    name: 'Leather Wallet',
    description: 'Slim leather wallet with multiple card slots.',
    longDescription:
      "This slim leather wallet is both stylish and functional, featuring multiple card slots and a compartment for bills. Made from high-quality leather, it offers durability and a sleek, minimalist design. It's the perfect accessory for carrying your essentials.",
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Accessories',
    image: 'https://example.com/images/leather_wallet.jpg',
    rating: 4.8,
    stock: 140,
    SKU: 'WALLET001',
  },
  {
    id: 21,
    name: 'Denim Shorts',
    description: 'Casual denim shorts with a frayed hem.',
    longDescription:
      'These casual denim shorts are perfect for warm weather, featuring a frayed hem and a relaxed fit. Made from soft, durable denim, they offer comfort and style. Pair them with a t-shirt or tank top for a laid-back summer look.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shorts',
    image: 'https://example.com/images/denim_shorts.jpg',
    rating: 4.3,
    stock: 100,
    SKU: 'SHORTS002',
  },
  {
    id: 22,
    name: 'Sweater Dress',
    description: 'Cozy sweater dress with a relaxed fit.',
    longDescription:
      "This cozy sweater dress is perfect for cooler days, offering warmth and comfort with a relaxed fit. Made from soft knit fabric, it's both stylish and comfortable. Dress it up with boots and accessories for a chic winter look.",
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Dresses',
    image: 'https://example.com/images/sweater_dress.jpg',
    rating: 4.7,
    stock: 60,
    SKU: 'DRESS001',
  },
  {
    id: 23,
    name: 'Leather Gloves',
    description: 'Elegant leather gloves with a warm lining.',
    longDescription:
      'These elegant leather gloves are both stylish and functional, featuring a warm lining for comfort during cold weather. Made from high-quality leather, they offer durability and a sophisticated look. Perfect for adding a touch of elegance to your winter outfits.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Accessories',
    image: 'https://example.com/images/leather_gloves.jpg',
    rating: 4.8,
    stock: 120,
    SKU: 'GLOVES001',
  },
  {
    id: 24,
    name: 'Windbreaker',
    description: 'Lightweight windbreaker with a hood.',
    longDescription:
      'This lightweight windbreaker is perfect for protecting against the wind and light rain. It features a hood for added coverage and zippered pockets to keep your belongings secure. The breathable fabric ensures comfort during outdoor activities.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Jackets',
    image: 'https://example.com/images/windbreaker.jpg',
    rating: 4.5,
    stock: 80,
    SKU: 'JACKET004',
  },
  {
    id: 25,
    name: 'Flannel Pajamas',
    description: 'Cozy flannel pajamas with a button-up top.',
    longDescription:
      "These cozy flannel pajamas are perfect for keeping warm during the colder months. The set includes a button-up top and matching pants, both made from soft, breathable flannel fabric. Available in a variety of patterns, they're perfect for a comfortable night's sleep.",
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Sleepwear',
    image: 'https://example.com/images/flannel_pajamas.jpg',
    rating: 4.7,
    stock: 90,
    SKU: 'PAJAMAS001',
  },
  {
    id: 26,
    name: 'Ankle Boots',
    description: 'Stylish ankle boots with a block heel.',
    longDescription:
      'These stylish ankle boots feature a block heel and a sleek design, making them perfect for both casual and formal occasions. Made from high-quality materials, they offer comfort and durability. Pair them with jeans or a dress for a versatile look.',
    price: 79.99,
    oldPrice: 99.99,
    discount: 20,
    category: 'Footwear',
    image: 'https://example.com/images/ankle_boots.jpg',
    rating: 4.6,
    stock: 70,
    SKU: 'BOOTS002',
  },
  {
    id: 27,
    name: 'Maxi Dress',
    description: 'Elegant maxi dress with a flowy silhouette.',
    longDescription:
      "This elegant maxi dress features a flowy silhouette and a flattering fit, making it perfect for special occasions. Made from lightweight fabric, it's comfortable and breathable. Available in multiple colors, it's a versatile piece that can be dressed up or down.",
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Dresses',
    image: 'https://example.com/images/maxi_dress.jpg',
    rating: 4.7,
    stock: 50,
    SKU: 'DRESS002',
  },
  {
    id: 28,
    name: 'Graphic Hoodie',
    description: 'Graphic hoodie with a bold print and cozy fit.',
    longDescription:
      'This graphic hoodie features a bold print and a cozy fit, making it perfect for casual wear. Made from soft, comfortable fabric, it provides warmth and style. The adjustable drawstring hood and kangaroo pocket add functionality.',
    price: 44.99,
    oldPrice: 59.99,
    discount: 25,
    category: 'Sweatshirts',
    image: 'https://example.com/images/graphic_hoodie.jpg',
    rating: 4.5,
    stock: 85,
    SKU: 'HOODIE002',
  },
  {
    id: 29,
    name: 'Trench Coat',
    description: 'Classic trench coat with a belted waist.',
    longDescription:
      "This classic trench coat is a timeless piece that adds sophistication to any outfit. Featuring a belted waist and a tailored fit, it's perfect for both casual and formal occasions. The water-resistant fabric makes it ideal for unpredictable weather.",
    price: 99.99,
    oldPrice: 129.99,
    discount: 23,
    category: 'Jackets',
    image: 'https://example.com/images/trench_coat.jpg',
    rating: 4.8,
    stock: 60,
    SKU: 'JACKET005',
  },
  {
    id: 30,
    name: 'Linen Shirt',
    description: 'Lightweight linen shirt with a relaxed fit.',
    longDescription:
      'This lightweight linen shirt is perfect for warm weather, offering breathability and comfort. The relaxed fit and classic design make it a versatile piece that can be dressed up or down. Pair it with jeans or shorts for a laid-back summer look.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Shirts',
    image: 'https://example.com/images/linen_shirt.jpg',
    rating: 4.4,
    stock: 95,
    SKU: 'SHIRT003',
  },
  {
    id: 31,
    name: 'High-Waisted Shorts',
    description: 'Trendy high-waisted shorts with a flattering fit.',
    longDescription:
      'These trendy high-waisted shorts are perfect for summer, offering a flattering fit and a stylish look. Made from soft, durable fabric, they are comfortable and versatile. Pair them with a crop top or a tucked-in blouse for a chic outfit.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shorts',
    image: 'https://example.com/images/high_waisted_shorts.jpg',
    rating: 4.5,
    stock: 100,
    SKU: 'SHORTS003',
  },
  {
    id: 32,
    name: 'Leather Jacket',
    description: 'Classic leather jacket with a zippered front.',
    longDescription:
      'This classic leather jacket is a must-have for any wardrobe, featuring a zippered front and a sleek design. Made from high-quality leather, it offers durability and a stylish look. Perfect for adding an edge to any outfit.',
    price: 199.99,
    oldPrice: 249.99,
    discount: 20,
    category: 'Jackets',
    image: 'https://example.com/images/leather_jacket.jpg',
    rating: 4.8,
    stock: 40,
    SKU: 'JACKET006',
  },
  {
    id: 33,
    name: 'Pleated Skirt',
    description: 'Chic pleated skirt with a midi length.',
    longDescription:
      'This chic pleated skirt features a midi length and a flowy silhouette, making it perfect for both casual and formal occasions. Made from lightweight fabric, it offers comfort and style. Pair it with a blouse or a sweater for a versatile look.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Skirts',
    image: 'https://example.com/images/pleated_skirt.jpg',
    rating: 4.7,
    stock: 70,
    SKU: 'SKIRT001',
  },
  {
    id: 34,
    name: 'Graphic Socks',
    description: 'Fun graphic socks with unique designs.',
    longDescription:
      "These fun graphic socks feature unique designs that add a pop of personality to any outfit. Made from soft, breathable fabric, they provide comfort and style. Available in a variety of patterns, they're perfect for everyday wear or as a gift.",
    price: 9.99,
    oldPrice: 12.99,
    discount: 23,
    category: 'Accessories',
    image: 'https://example.com/images/graphic_socks.jpg',
    rating: 4.6,
    stock: 150,
    SKU: 'SOCKS001',
  },
  {
    id: 35,
    name: 'Ruffle Blouse',
    description: 'Elegant ruffle blouse with a lightweight fabric.',
    longDescription:
      'This elegant ruffle blouse features a lightweight fabric and a feminine design, making it perfect for both casual and formal occasions. The ruffle details add a touch of sophistication, while the relaxed fit ensures comfort. Pair it with a skirt or trousers for a chic look.',
    price: 34.99,
    oldPrice: 44.99,
    discount: 22,
    category: 'Blouses',
    image: 'https://example.com/images/ruffle_blouse.jpg',
    rating: 4.5,
    stock: 95,
    SKU: 'BLOUSE001',
  },
  {
    id: 36,
    name: 'Oversized Sweater',
    description: 'Cozy oversized sweater with a relaxed fit.',
    longDescription:
      'This cozy oversized sweater is perfect for lounging or casual outings. Made from soft, warm fabric, it provides comfort and style. The relaxed fit makes it easy to layer over your favorite outfits. Available in multiple colors.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Sweaters',
    image: 'https://example.com/images/oversized_sweater.jpg',
    rating: 4.7,
    stock: 80,
    SKU: 'SWEATER001',
  },
  {
    id: 37,
    name: 'Cropped Denim Jacket',
    description: 'Trendy cropped denim jacket with a frayed hem.',
    longDescription:
      'This trendy cropped denim jacket features a frayed hem and a fitted silhouette, making it perfect for layering over dresses or high-waisted pants. Made from durable denim, it offers both style and comfort. A versatile piece that adds a cool, edgy vibe to any outfit.',
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Jackets',
    image: 'https://example.com/images/cropped_denim_jacket.jpg',
    rating: 4.5,
    stock: 65,
    SKU: 'JACKET007',
  },
  {
    id: 38,
    name: 'Corduroy Pants',
    description: 'Stylish corduroy pants with a straight leg fit.',
    longDescription:
      'These stylish corduroy pants feature a straight leg fit and a soft, textured fabric. Perfect for adding a touch of vintage flair to your wardrobe, they are comfortable and versatile. Pair them with a sweater or blouse for a polished look.',
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Pants',
    image: 'https://example.com/images/corduroy_pants.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'PANTS003',
  },
  {
    id: 39,
    name: 'Silk Scarf',
    description: 'Elegant silk scarf with a delicate pattern.',
    longDescription:
      'This elegant silk scarf features a delicate pattern and a luxurious feel, making it the perfect accessory to elevate any outfit. Made from high-quality silk, it offers a soft touch and a sophisticated look. Available in various colors and designs.',
    price: 24.99,
    oldPrice: 34.99,
    discount: 29,
    category: 'Accessories',
    image: 'https://example.com/images/silk_scarf.jpg',
    rating: 4.8,
    stock: 100,
    SKU: 'SCARF001',
  },
  {
    id: 40,
    name: 'Wool Coat',
    description: 'Warm wool coat with a tailored fit.',
    longDescription:
      'This warm wool coat is a winter essential, offering a tailored fit and a sophisticated design. Made from high-quality wool, it provides insulation against the cold while maintaining a sleek appearance. The coat features a button-up front and deep pockets for added functionality.',
    price: 149.99,
    oldPrice: 199.99,
    discount: 25,
    category: 'Jackets',
    image: 'https://example.com/images/wool_coat.jpg',
    rating: 4.8,
    stock: 55,
    SKU: 'JACKET008',
  },
]

export const ProductsUUID = [
  {
    id: 1,
    name: 'Basic T-Shirt',
    description: '100% cotton basic t-shirt, available in various colors.',
    longDescription:
      "This basic t-shirt is made from 100% premium cotton, ensuring a soft and comfortable feel. It's perfect for layering or wearing on its own. Available in a range of colors to suit any wardrobe, this tee is a versatile staple you'll reach for again and again.",
    price: 19.99,
    oldPrice: 24.99,
    discount: 20,
    category: 'T-Shirts',
    image: 'https://example.com/images/basic_tshirt.jpg',
    rating: 4.5,
    stock: 120,
    SKU: 'TSHIRT001',
    uuid: '91845856-34f8-44f2-8e45-4c745eaa30ad',
  },
  {
    id: 2,
    name: 'Slim Fit Jeans',
    description: 'Slim fit jeans with a modern cut, perfect for casual wear.',
    longDescription:
      'These slim fit jeans are designed with a modern, flattering cut that hugs your body while still providing comfort. Made from high-quality denim, they are durable and long-lasting, making them a perfect choice for both casual and semi-formal occasions.',
    price: 49.99,
    oldPrice: 59.99,
    discount: 17,
    category: 'Jeans',
    image: 'https://example.com/images/slim_fit_jeans.jpg',
    rating: 4.3,
    stock: 80,
    SKU: 'JEANS001',
    uuid: '185c6bc6-55ad-4070-b6ec-194e0a80a62d',
  },
  {
    id: 3,
    name: 'Denim Jacket',
    description: 'Classic denim jacket with button front closure.',
    longDescription:
      "Our classic denim jacket features a button front closure and is crafted from durable denim. It's a timeless piece that pairs perfectly with any outfit, providing both style and warmth. Whether you're dressing up or down, this jacket is a must-have.",
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Jackets',
    image: 'https://example.com/images/denim_jacket.jpg',
    rating: 4.7,
    stock: 50,
    SKU: 'JACKET001',
    uuid: '3ed1bf7e-0a85-4273-8200-1bb1998d536e',
  },
  {
    id: 4,
    name: 'Chino Pants',
    description: 'Comfortable and stylish chino pants for everyday wear.',
    longDescription:
      "These chino pants combine comfort and style, making them ideal for everyday wear. Made from soft, breathable fabric, they offer a tailored fit that's perfect for the office or a night out. Available in multiple colors to complement any look.",
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Pants',
    image: 'https://example.com/images/chino_pants.jpg',
    rating: 4.4,
    stock: 100,
    SKU: 'PANTS001',
    uuid: '34363922-bc18-41b1-af44-1ec7a343236c',
  },
  {
    id: 5,
    name: 'Plaid Shirt',
    description: 'Casual plaid shirt made from soft flannel fabric.',
    longDescription:
      "This plaid shirt is crafted from soft flannel fabric, providing comfort and warmth. It's perfect for layering during the cooler months or wearing on its own for a laid-back look. The classic plaid pattern adds a touch of rugged style to any outfit.",
    price: 29.99,
    oldPrice: 34.99,
    discount: 14,
    category: 'Shirts',
    image: 'https://example.com/images/plaid_shirt.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'SHIRT001',
    uuid: 'a47e1993-0426-41c4-80d0-5bda2a490430',
  },
  {
    id: 6,
    name: 'Leather Belt',
    description: 'Genuine leather belt with a classic buckle.',
    longDescription:
      "This genuine leather belt is a timeless accessory that adds a touch of sophistication to any outfit. Featuring a classic metal buckle, it's perfect for both casual and formal wear. The durable leather ensures it will be a long-lasting addition to your wardrobe.",
    price: 19.99,
    oldPrice: 24.99,
    discount: 20,
    category: 'Accessories',
    image: 'https://example.com/images/leather_belt.jpg',
    rating: 4.8,
    stock: 200,
    SKU: 'BELT001',
    uuid: '35b9171b-41ae-4aa2-9d64-e9c8293c2cae',
  },
  {
    id: 7,
    name: 'Sneakers',
    description: 'Comfortable sneakers for everyday wear.',
    longDescription:
      'These sneakers are designed for comfort and durability, making them perfect for everyday wear. With a cushioned sole and breathable upper, they provide support and ventilation during all your daily activities. Available in multiple colors and styles.',
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Footwear',
    image: 'https://example.com/images/sneakers.jpg',
    rating: 4.5,
    stock: 150,
    SKU: 'SHOE001',
    uuid: '11b48ada-c67c-434d-a6f7-76675be33784',
  },
  {
    id: 8,
    name: 'Wool Scarf',
    description: 'Soft wool scarf to keep you warm during winter.',
    longDescription:
      'This wool scarf is a winter essential, crafted from soft, high-quality wool. It provides excellent warmth and comfort, while its classic design makes it a versatile accessory that can be paired with any outfit.',
    price: 25.99,
    oldPrice: 32.99,
    discount: 21,
    category: 'Accessories',
    image: 'https://example.com/images/wool_scarf.jpg',
    rating: 4.7,
    stock: 180,
    SKU: 'SCARF001',
    uuid: 'e2c9d3ac-e06d-4ebb-b0d6-395054193fe2',
  },
  {
    id: 9,
    name: 'Puffer Jacket',
    description: 'Lightweight and warm puffer jacket, perfect for winter.',
    longDescription:
      'Stay warm without the bulk in this lightweight puffer jacket. Filled with high-quality insulation, it provides excellent warmth while remaining lightweight and comfortable. The jacket is also water-resistant, making it perfect for winter weather.',
    price: 89.99,
    oldPrice: 119.99,
    discount: 25,
    category: 'Jackets',
    image: 'https://example.com/images/puffer_jacket.jpg',
    rating: 4.6,
    stock: 70,
    SKU: 'JACKET002',
    uuid: '2e92a9f5-73f3-4b71-8d94-43620485f6e5',
  },
  {
    id: 10,
    name: 'Graphic Tee',
    description: 'Trendy graphic t-shirt with unique print.',
    longDescription:
      "Make a statement with this trendy graphic tee. Featuring a unique print, it's made from soft, breathable fabric for all-day comfort. Pair it with jeans or shorts for a casual, stylish look.",
    price: 22.99,
    oldPrice: 29.99,
    discount: 23,
    category: 'T-Shirts',
    image: 'https://example.com/images/graphic_tee.jpg',
    rating: 4.3,
    stock: 130,
    SKU: 'TSHIRT002',
    uuid: 'fcac23da-33fc-4cbb-8790-dbe0152b82f9',
  },
  {
    id: 11,
    name: 'Hoodie',
    description: 'Cozy hoodie made from soft fleece.',
    longDescription:
      'This cozy hoodie is perfect for lounging or casual outings. Made from soft fleece, it provides warmth and comfort without being too heavy. The adjustable drawstring hood and kangaroo pocket add functionality and style.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Sweatshirts',
    image: 'https://example.com/images/hoodie.jpg',
    rating: 4.7,
    stock: 90,
    SKU: 'HOODIE001',
    uuid: '10c2ac86-3e58-4e80-88f1-bfadde573c32',
  },
  {
    id: 12,
    name: 'Canvas Tote Bag',
    description: 'Durable canvas tote bag, perfect for shopping.',
    longDescription:
      "This durable canvas tote bag is perfect for shopping or carrying everyday essentials. Made from heavy-duty canvas, it features sturdy handles and a spacious interior. Available in multiple colors, it's both practical and stylish.",
    price: 15.99,
    oldPrice: 19.99,
    discount: 20,
    category: 'Bags',
    image: 'https://example.com/images/canvas_tote.jpg',
    rating: 4.8,
    stock: 200,
    SKU: 'BAG001',
    uuid: 'c6ea95fb-bb46-4cf5-b8be-ed3ea379dc72',
  },
  {
    id: 13,
    name: 'Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric.',
    longDescription:
      'These lightweight running shorts are designed for performance and comfort. Made from moisture-wicking fabric, they keep you cool and dry during your workouts. The elastic waistband ensures a secure fit, and the built-in liner provides additional support.',
    price: 25.99,
    oldPrice: 32.99,
    discount: 21,
    category: 'Shorts',
    image: 'https://example.com/images/running_shorts.jpg',
    rating: 4.4,
    stock: 140,
    SKU: 'SHORTS001',
    uuid: '8d67297e-f095-41e7-893b-6127d6643589',
  },
  {
    id: 14,
    name: 'Polo Shirt',
    description: 'Classic polo shirt with a ribbed collar.',
    longDescription:
      "This classic polo shirt features a ribbed collar and a comfortable, relaxed fit. Made from breathable cotton fabric, it's perfect for both casual and semi-formal occasions. The versatile design makes it a wardrobe essential.",
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shirts',
    image: 'https://example.com/images/polo_shirt.jpg',
    rating: 4.5,
    stock: 110,
    SKU: 'SHIRT002',
    uuid: 'a21b7bad-4e01-48f9-b52c-2a4659ea22ca',
  },
  {
    id: 15,
    name: 'Winter Boots',
    description: 'Sturdy winter boots with waterproof exterior.',
    longDescription:
      'These sturdy winter boots are designed to keep your feet warm and dry in harsh weather conditions. Featuring a waterproof exterior and insulated lining, they provide excellent protection against the elements. The rugged sole ensures traction on slippery surfaces.',
    price: 99.99,
    oldPrice: 129.99,
    discount: 23,
    category: 'Footwear',
    image: 'https://example.com/images/winter_boots.jpg',
    rating: 4.7,
    stock: 60,
    SKU: 'BOOTS001',
    uuid: '96402453-e876-4d44-8e75-559494bea40c',
  },
  {
    id: 16,
    name: 'Cargo Pants',
    description: 'Comfortable cargo pants with multiple pockets.',
    longDescription:
      'These comfortable cargo pants are perfect for outdoor activities or casual wear. Made from durable fabric, they feature multiple pockets for storing your essentials. The relaxed fit and adjustable waistband provide comfort and functionality.',
    price: 45.99,
    oldPrice: 59.99,
    discount: 23,
    category: 'Pants',
    image: 'https://example.com/images/cargo_pants.jpg',
    rating: 4.4,
    stock: 85,
    SKU: 'PANTS002',
    uuid: '4f5fc22c-1ccb-4b18-ae84-37bc4eee97de',
  },
  {
    id: 17,
    name: 'Fleece Jacket',
    description: 'Warm fleece jacket with zippered pockets.',
    longDescription:
      'This warm fleece jacket is perfect for layering during the colder months. It features zippered pockets to keep your essentials secure and a full-zip front for easy wear. The soft fleece material provides comfort and warmth without adding bulk.',
    price: 49.99,
    oldPrice: 69.99,
    discount: 28,
    category: 'Jackets',
    image: 'https://example.com/images/fleece_jacket.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'JACKET003',
    uuid: '366fbda2-29e2-4e06-a7e9-a9105b147d02',
  },
  {
    id: 18,
    name: 'Sports Bra',
    description: 'High-impact sports bra with moisture-wicking fabric.',
    longDescription:
      'This high-impact sports bra is designed to provide support and comfort during intense workouts. Made from moisture-wicking fabric, it keeps you cool and dry. The adjustable straps and wide band offer a secure and customized fit.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Activewear',
    image: 'https://example.com/images/sports_bra.jpg',
    rating: 4.5,
    stock: 90,
    SKU: 'ACTIVE001',
    uuid: 'a7f9625b-54f5-4be4-9f41-2223c4f6f6e1',
  },
  {
    id: 19,
    name: 'Yoga Pants',
    description: 'Flexible and comfortable yoga pants with a high waistband.',
    longDescription:
      'These yoga pants are designed for flexibility and comfort, with a high waistband that provides support and coverage. The stretchy fabric allows for a full range of motion, making them perfect for yoga, Pilates, or any other workout.',
    price: 34.99,
    oldPrice: 44.99,
    discount: 22,
    category: 'Activewear',
    image: 'https://example.com/images/yoga_pants.jpg',
    rating: 4.7,
    stock: 100,
    SKU: 'ACTIVE002',
    uuid: '13b55e3d-636f-4975-b542-a6703853ced6',
  },
  {
    id: 20,
    name: 'Leather Wallet',
    description: 'Slim leather wallet with multiple card slots.',
    longDescription:
      "This slim leather wallet is both stylish and functional, featuring multiple card slots and a compartment for bills. Made from high-quality leather, it offers durability and a sleek, minimalist design. It's the perfect accessory for carrying your essentials.",
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Accessories',
    image: 'https://example.com/images/leather_wallet.jpg',
    rating: 4.8,
    stock: 140,
    SKU: 'WALLET001',
    uuid: 'ff0d3cba-d9fa-418b-b4d1-8c8aa2bc47b2',
  },
  {
    id: 21,
    name: 'Denim Shorts',
    description: 'Casual denim shorts with a frayed hem.',
    longDescription:
      'These casual denim shorts are perfect for warm weather, featuring a frayed hem and a relaxed fit. Made from soft, durable denim, they offer comfort and style. Pair them with a t-shirt or tank top for a laid-back summer look.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shorts',
    image: 'https://example.com/images/denim_shorts.jpg',
    rating: 4.3,
    stock: 100,
    SKU: 'SHORTS002',
    uuid: '2e893819-a3f3-4fcc-97fd-0b5cedbb33ec',
  },
  {
    id: 22,
    name: 'Sweater Dress',
    description: 'Cozy sweater dress with a relaxed fit.',
    longDescription:
      "This cozy sweater dress is perfect for cooler days, offering warmth and comfort with a relaxed fit. Made from soft knit fabric, it's both stylish and comfortable. Dress it up with boots and accessories for a chic winter look.",
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Dresses',
    image: 'https://example.com/images/sweater_dress.jpg',
    rating: 4.7,
    stock: 60,
    SKU: 'DRESS001',
    uuid: 'db50d67c-f2ed-49a4-853c-4a7cba2f2030',
  },
  {
    id: 23,
    name: 'Leather Gloves',
    description: 'Elegant leather gloves with a warm lining.',
    longDescription:
      'These elegant leather gloves are both stylish and functional, featuring a warm lining for comfort during cold weather. Made from high-quality leather, they offer durability and a sophisticated look. Perfect for adding a touch of elegance to your winter outfits.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Accessories',
    image: 'https://example.com/images/leather_gloves.jpg',
    rating: 4.8,
    stock: 120,
    SKU: 'GLOVES001',
    uuid: '3a40ebea-2b8b-4f69-8fec-43d968864a5a',
  },
  {
    id: 24,
    name: 'Windbreaker',
    description: 'Lightweight windbreaker with a hood.',
    longDescription:
      'This lightweight windbreaker is perfect for protecting against the wind and light rain. It features a hood for added coverage and zippered pockets to keep your belongings secure. The breathable fabric ensures comfort during outdoor activities.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Jackets',
    image: 'https://example.com/images/windbreaker.jpg',
    rating: 4.5,
    stock: 80,
    SKU: 'JACKET004',
    uuid: 'c375c739-1d4f-44b7-88c7-31f32fcb9d59',
  },
  {
    id: 25,
    name: 'Flannel Pajamas',
    description: 'Cozy flannel pajamas with a button-up top.',
    longDescription:
      "These cozy flannel pajamas are perfect for keeping warm during the colder months. The set includes a button-up top and matching pants, both made from soft, breathable flannel fabric. Available in a variety of patterns, they're perfect for a comfortable night's sleep.",
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Sleepwear',
    image: 'https://example.com/images/flannel_pajamas.jpg',
    rating: 4.7,
    stock: 90,
    SKU: 'PAJAMAS001',
    uuid: '13072475-242c-49f4-9dc1-6612eeb20364',
  },
  {
    id: 26,
    name: 'Ankle Boots',
    description: 'Stylish ankle boots with a block heel.',
    longDescription:
      'These stylish ankle boots feature a block heel and a sleek design, making them perfect for both casual and formal occasions. Made from high-quality materials, they offer comfort and durability. Pair them with jeans or a dress for a versatile look.',
    price: 79.99,
    oldPrice: 99.99,
    discount: 20,
    category: 'Footwear',
    image: 'https://example.com/images/ankle_boots.jpg',
    rating: 4.6,
    stock: 70,
    SKU: 'BOOTS002',
    uuid: 'c56fccaf-a9a2-4206-ab74-11b7952dd7d1',
  },
  {
    id: 27,
    name: 'Maxi Dress',
    description: 'Elegant maxi dress with a flowy silhouette.',
    longDescription:
      "This elegant maxi dress features a flowy silhouette and a flattering fit, making it perfect for special occasions. Made from lightweight fabric, it's comfortable and breathable. Available in multiple colors, it's a versatile piece that can be dressed up or down.",
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Dresses',
    image: 'https://example.com/images/maxi_dress.jpg',
    rating: 4.7,
    stock: 50,
    SKU: 'DRESS002',
    uuid: '56f5f035-dcd6-4bd8-aa62-0519af00c913',
  },
  {
    id: 28,
    name: 'Graphic Hoodie',
    description: 'Graphic hoodie with a bold print and cozy fit.',
    longDescription:
      'This graphic hoodie features a bold print and a cozy fit, making it perfect for casual wear. Made from soft, comfortable fabric, it provides warmth and style. The adjustable drawstring hood and kangaroo pocket add functionality.',
    price: 44.99,
    oldPrice: 59.99,
    discount: 25,
    category: 'Sweatshirts',
    image: 'https://example.com/images/graphic_hoodie.jpg',
    rating: 4.5,
    stock: 85,
    SKU: 'HOODIE002',
    uuid: 'ea8425ee-4844-4d5f-b92a-39bfe7976efd',
  },
  {
    id: 29,
    name: 'Trench Coat',
    description: 'Classic trench coat with a belted waist.',
    longDescription:
      "This classic trench coat is a timeless piece that adds sophistication to any outfit. Featuring a belted waist and a tailored fit, it's perfect for both casual and formal occasions. The water-resistant fabric makes it ideal for unpredictable weather.",
    price: 99.99,
    oldPrice: 129.99,
    discount: 23,
    category: 'Jackets',
    image: 'https://example.com/images/trench_coat.jpg',
    rating: 4.8,
    stock: 60,
    SKU: 'JACKET005',
    uuid: '993b64d9-1c2b-4f0d-adc1-2d4eeec02b34',
  },
  {
    id: 30,
    name: 'Linen Shirt',
    description: 'Lightweight linen shirt with a relaxed fit.',
    longDescription:
      'This lightweight linen shirt is perfect for warm weather, offering breathability and comfort. The relaxed fit and classic design make it a versatile piece that can be dressed up or down. Pair it with jeans or shorts for a laid-back summer look.',
    price: 39.99,
    oldPrice: 49.99,
    discount: 20,
    category: 'Shirts',
    image: 'https://example.com/images/linen_shirt.jpg',
    rating: 4.4,
    stock: 95,
    SKU: 'SHIRT003',
    uuid: 'bb9cd2e5-153e-4b79-a55a-660d182b021e',
  },
  {
    id: 31,
    name: 'High-Waisted Shorts',
    description: 'Trendy high-waisted shorts with a flattering fit.',
    longDescription:
      'These trendy high-waisted shorts are perfect for summer, offering a flattering fit and a stylish look. Made from soft, durable fabric, they are comfortable and versatile. Pair them with a crop top or a tucked-in blouse for a chic outfit.',
    price: 29.99,
    oldPrice: 39.99,
    discount: 25,
    category: 'Shorts',
    image: 'https://example.com/images/high_waisted_shorts.jpg',
    rating: 4.5,
    stock: 100,
    SKU: 'SHORTS003',
    uuid: '25d48f99-1edd-4a00-a89a-7b864cfb6ebe',
  },
  {
    id: 32,
    name: 'Leather Jacket',
    description: 'Classic leather jacket with a zippered front.',
    longDescription:
      'This classic leather jacket is a must-have for any wardrobe, featuring a zippered front and a sleek design. Made from high-quality leather, it offers durability and a stylish look. Perfect for adding an edge to any outfit.',
    price: 199.99,
    oldPrice: 249.99,
    discount: 20,
    category: 'Jackets',
    image: 'https://example.com/images/leather_jacket.jpg',
    rating: 4.8,
    stock: 40,
    SKU: 'JACKET006',
    uuid: 'c3cb3daf-6154-456f-8c95-22f60dcd7c18',
  },
  {
    id: 33,
    name: 'Pleated Skirt',
    description: 'Chic pleated skirt with a midi length.',
    longDescription:
      'This chic pleated skirt features a midi length and a flowy silhouette, making it perfect for both casual and formal occasions. Made from lightweight fabric, it offers comfort and style. Pair it with a blouse or a sweater for a versatile look.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Skirts',
    image: 'https://example.com/images/pleated_skirt.jpg',
    rating: 4.7,
    stock: 70,
    SKU: 'SKIRT001',
    uuid: '7eca8928-0305-46a5-be74-6b7df1089b82',
  },
  {
    id: 34,
    name: 'Graphic Socks',
    description: 'Fun graphic socks with unique designs.',
    longDescription:
      "These fun graphic socks feature unique designs that add a pop of personality to any outfit. Made from soft, breathable fabric, they provide comfort and style. Available in a variety of patterns, they're perfect for everyday wear or as a gift.",
    price: 9.99,
    oldPrice: 12.99,
    discount: 23,
    category: 'Accessories',
    image: 'https://example.com/images/graphic_socks.jpg',
    rating: 4.6,
    stock: 150,
    SKU: 'SOCKS001',
    uuid: 'd324d4c6-0956-4d35-a451-d1d712ad3d8e',
  },
  {
    id: 35,
    name: 'Ruffle Blouse',
    description: 'Elegant ruffle blouse with a lightweight fabric.',
    longDescription:
      'This elegant ruffle blouse features a lightweight fabric and a feminine design, making it perfect for both casual and formal occasions. The ruffle details add a touch of sophistication, while the relaxed fit ensures comfort. Pair it with a skirt or trousers for a chic look.',
    price: 34.99,
    oldPrice: 44.99,
    discount: 22,
    category: 'Blouses',
    image: 'https://example.com/images/ruffle_blouse.jpg',
    rating: 4.5,
    stock: 95,
    SKU: 'BLOUSE001',
    uuid: 'c8c5b008-9895-4c9e-a7d1-e1b7c7967a33',
  },
  {
    id: 36,
    name: 'Oversized Sweater',
    description: 'Cozy oversized sweater with a relaxed fit.',
    longDescription:
      'This cozy oversized sweater is perfect for lounging or casual outings. Made from soft, warm fabric, it provides comfort and style. The relaxed fit makes it easy to layer over your favorite outfits. Available in multiple colors.',
    price: 49.99,
    oldPrice: 64.99,
    discount: 23,
    category: 'Sweaters',
    image: 'https://example.com/images/oversized_sweater.jpg',
    rating: 4.7,
    stock: 80,
    SKU: 'SWEATER001',
    uuid: '1204a2d4-d496-4a02-9ef2-9cb6b6fb3a81',
  },
  {
    id: 37,
    name: 'Cropped Denim Jacket',
    description: 'Trendy cropped denim jacket with a frayed hem.',
    longDescription:
      'This trendy cropped denim jacket features a frayed hem and a fitted silhouette, making it perfect for layering over dresses or high-waisted pants. Made from durable denim, it offers both style and comfort. A versatile piece that adds a cool, edgy vibe to any outfit.',
    price: 69.99,
    oldPrice: 89.99,
    discount: 22,
    category: 'Jackets',
    image: 'https://example.com/images/cropped_denim_jacket.jpg',
    rating: 4.5,
    stock: 65,
    SKU: 'JACKET007',
    uuid: '60aa8362-897e-43ba-8f90-c7e8dab3b96f',
  },
  {
    id: 38,
    name: 'Corduroy Pants',
    description: 'Stylish corduroy pants with a straight leg fit.',
    longDescription:
      'These stylish corduroy pants feature a straight leg fit and a soft, textured fabric. Perfect for adding a touch of vintage flair to your wardrobe, they are comfortable and versatile. Pair them with a sweater or blouse for a polished look.',
    price: 59.99,
    oldPrice: 79.99,
    discount: 25,
    category: 'Pants',
    image: 'https://example.com/images/corduroy_pants.jpg',
    rating: 4.6,
    stock: 75,
    SKU: 'PANTS003',
    uuid: 'c7c17c7a-b02c-472f-9b81-ef8e0daa2b84',
  },
  {
    id: 39,
    name: 'Silk Scarf',
    description: 'Elegant silk scarf with a delicate pattern.',
    longDescription:
      'This elegant silk scarf features a delicate pattern and a luxurious feel, making it the perfect accessory to elevate any outfit. Made from high-quality silk, it offers a soft touch and a sophisticated look. Available in various colors and designs.',
    price: 24.99,
    oldPrice: 34.99,
    discount: 29,
    category: 'Accessories',
    image: 'https://example.com/images/silk_scarf.jpg',
    rating: 4.8,
    stock: 100,
    SKU: 'SCARF001',
    uuid: '3afac75f-70b1-40c4-9205-e31982240214',
  },
  {
    id: 40,
    name: 'Wool Coat',
    description: 'Warm wool coat with a tailored fit.',
    longDescription:
      'This warm wool coat is a winter essential, offering a tailored fit and a sophisticated design. Made from high-quality wool, it provides insulation against the cold while maintaining a sleek appearance. The coat features a button-up front and deep pockets for added functionality.',
    price: 149.99,
    oldPrice: 199.99,
    discount: 25,
    category: 'Jackets',
    image: 'https://example.com/images/wool_coat.jpg',
    rating: 4.8,
    stock: 55,
    SKU: 'JACKET008',
    uuid: '6f727714-a6ff-427e-b270-7f7c8b866750',
  },
]

export const filterMenu = (): string[] => {
  const uniqueItemsMap = new Map()
  ProductsUUID.forEach(item => {
    if (!uniqueItemsMap.has(item.category)) {
      uniqueItemsMap.set(item.category, item.category)
    }
  })
  return Array.from(uniqueItemsMap.values())
}
